version: '3'

services:
  hellonetcore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  helloapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat


